# Generated by Django 4.2.1 on 2023-11-19 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Encrypt', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadFileForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('file', models.FileField(default=None, max_length=30, null=True, upload_to='')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Upload',
        ),
    ]
