# Generated by Django 4.2.1 on 2023-11-19 14:55

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Encrypt', '0002_uploadfileform_delete_upload'),
    ]

    operations = [
        migrations.CreateModel(
            name='Upload1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('name', models.CharField(max_length=100)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='UploadFileForm',
        ),
    ]
